---
- name: Install Aptitude
  become: yes
  apt: pkg=aptitude state=latest

- name: Apply Patches
  become: yes
  apt:
    state: latest
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl

- debug: var=ansible_ssh_host
- debug: var=inventory_hostname

- name: "Reboot if required"
  shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
  become: true
  async: 1
  poll: 0
  ignore_errors: true

# - name: "Wait for reboot"
#   local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started
#   become: false
