---
# Playbook: Patch OS and Reboot

- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  name: Install Operating System Patches
  become: yes

  tasks:
  - name: Ensure Package Aptitude is installed
    apt:
      state: latest
      update_cache: yes
      cache_valid_time: 3600
      pkg: aptitude

  - name: Apply Latest OS Patches
    apt:
      state: latest
      upgrade: yes

  - name: Ensure Common System Packages are installed
    apt:
      state: latest
      pkg: "{{ item }}"
    with_items:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl

  - name: Reboot if necessary
    shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
    async: 1
    poll: 0
    ignore_errors: true
