---

- name: add webupd8 ppa
  apt_repository:
    repo: ppa:webupd8team/java
    update_cache: yes
    state: present

- name: Add Casandra repository and update apt cache
  apt_repository:
    repo: "{{ cassandra_apt_repository }}"
    update_cache: yes
    state: present

- name: Add Cassandra public key
  apt_key:
    url: "{{ cassandra_apt_key_url }}"
    state: present

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Ensure Java and Cassandra are installed
  apt:
    update_cache: yes
    state: latest
    pkg: "{{ item }}"
  with_items:
    - oracle-java8-installer
    - cassandra
  when: ansible_os_family|lower == 'debian'
  register: deb_install

#- debug: var=deb_install

- name: Check for pointers of first install - default cluster_name
  shell: grep cluster_name {{ cassandra_conf_dir }}/cassandra.yaml
  register: result

#- debug: var=result

- name: Stop cassandra if first install
  service: name=cassandra state=stopped
  when: deb_install|changed and result.stdout.find('Test Cluster') != -1 or cassandra_reinitialize_cluster

- name: Remove default cluster_name from the system table of first install
  file: path={{ cassandra_home_dir }}/{{ item }} state=absent
  when: deb_install|changed and result.stdout.find('Test Cluster') != -1 or cassandra_reinitialize_cluster
  with_items:
    - data
    - commitlog
    - saved_caches

- include: fqdn.yml
  when: cassandra_seeds_fqdns

- name: Get stats of cassandra conf dir
  stat: path={{ cassandra_conf_dir }}
  register: sym

#- debug: var=sym

- name: Remove symlink file of cassandra conf dir
  file:
    path:  "{{ cassandra_conf_dir }}"
    state: absent
  when: sym.stat.islnk|default(false)

- name: Create cassandra.yaml config file
  template:
    src:   cassandra.yaml.j2
    dest:  "{{ cassandra_conf_dir }}/cassandra.yaml"
    owner: root
    group: root
    mode:  0644
  notify:
    - Restart cassandra

- name: Create other cassandra config files
  template:
    src:   "{{ item }}.j2"
    dest:  "{{ cassandra_conf_dir }}/{{ item }}"
    owner: root
    group: root
    mode:  0644
  with_items:
    - cassandra-env.sh
    - cassandra-rackdc.properties
    - commitlog_archiving.properties
  notify:
    - Restart cassandra

- name: Create cassandra triggers directory
  file:
    path:  "{{ cassandra_conf_dir }}/triggers"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode:  0755
    state: directory

- name: Create cassandra default settings file
  template:
    src:   etc.default.cassandra.j2
    dest:  "/etc/default/cassandra"
    owner: root
    group: root
    mode:  0644
  notify:
    - Restart cassandra

- name: Ensure correct cassandra directories ownership and permission
  file:
    path:  "{{ item }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode:  0755
    state: directory
  with_items:
    - "{{ cassandra_log_dir }}"
    - "{{ cassandra_home_dir }}"
    - "{{ cassandra_pid_dir }}"
  notify:
    - Restart cassandra

- name: Start cassandra
  service: name=cassandra enabled=yes state=started
