- name: Create Developer Group
  group: name=developers state=present

- name: Create User
  user: name=johndoe shell=/bin/bash group=developers

- name: Add Authorized Key
  authorized_key: user=johndoe key="{{ item }}"
  with_file:
    - files/id_rsa_johndoe.pub
