---
- name: Set UName Property
  shell: uname -r
  ignore_errors: yes
  register: uname_result
- debug: msg="{{ uname_result.stdout }}"

- name: Set Current User
  shell: whoami
  register: user
- debug: msg="{{ user.stdout }} "

- name: Add Docker repository key
  become: yes
  apt_key:
    id: "{{ docker_apt_key_sig }}"
    url: "{{ docker_apt_key_url }}"
    state: present

- name: Add Docker repository and update apt cache
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: yes
    state: present

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - linux-image-extra-{{ uname_result.stdout }}
    - linux-image-extra-virtual
    - docker-ce
    - python-dev
    - python-pip


  # ATTENTION: this task can potentially create new users!
- name: Add users to the docker group
  become: yes
  user:
    name: "{{ user.stdout }}"
    groups: docker
    append: yes

- name: Start docker.io
  service:
    name: docker
    state: started

- name: Upgrade latest pip and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: pip, version: 9.0.1 }
    - { name: docker-compose, version: 1.14.0 }
  when: item.version=="latest"
